//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CVL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backup directory has not been configured and the default backup directory could not be created. Please specify this location in the settings..
        /// </summary>
        internal static string err_BackupNotConfigured {
            get {
                return ResourceManager.GetString("err_BackupNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valheim failed to launch.
        /// </summary>
        internal static string err_FailedLaunchValheim {
            get {
                return ResourceManager.GetString("err_FailedLaunchValheim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your settings from the previous version failed to migrate to this version.
        /// </summary>
        internal static string err_FailedSettingsUpgrade {
            get {
                return ResourceManager.GetString("err_FailedSettingsUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valheim no longer exists in the directory specified. Please update your settings and try again..
        /// </summary>
        internal static string err_LaunchValheimMissing {
            get {
                return ResourceManager.GetString("err_LaunchValheimMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVL Attempted to launch valheim but the application hasn&apos;t been detected. Please try again..
        /// </summary>
        internal static string err_LaunchValheimProcessFailed {
            get {
                return ResourceManager.GetString("err_LaunchValheimProcessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Valheim installation directory is not configured and could not be found. Please specify the installation directory manually in the settings..
        /// </summary>
        internal static string err_ValheimNotConfigured {
            get {
                return ResourceManager.GetString("err_ValheimNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_close {
            get {
                object obj = ResourceManager.GetObject("icon_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_settings {
            get {
                object obj = ResourceManager.GetObject("icon_settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running backup ... .
        /// </summary>
        internal static string info_BackupRunning {
            get {
                return ResourceManager.GetString("info_BackupRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing backups more than one month old.
        /// </summary>
        internal static string info_BackupsClearingOld {
            get {
                return ResourceManager.GetString("info_BackupsClearingOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backups are disabled.
        /// </summary>
        internal static string info_BackupsDisabled {
            get {
                return ResourceManager.GetString("info_BackupsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup system is ready.
        /// </summary>
        internal static string info_BackupsReady {
            get {
                return ResourceManager.GetString("info_BackupsReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization complete.
        /// </summary>
        internal static string info_InitializationComplete {
            get {
                return ResourceManager.GetString("info_InitializationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading server list ... .
        /// </summary>
        internal static string info_LoadingServers {
            get {
                return ResourceManager.GetString("info_LoadingServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your settings from the previous version of CVL have been upgraded to this version.
        /// </summary>
        internal static string info_SettingsUpgraded {
            get {
                return ResourceManager.GetString("info_SettingsUpgraded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valheim ready to launch.
        /// </summary>
        internal static string info_ValheimReady {
            get {
                return ResourceManager.GetString("info_ValheimReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to complete.
        /// </summary>
        internal static string keyword_Complete {
            get {
                return ResourceManager.GetString("keyword_Complete", resourceCulture);
            }
        }
    }
}
